import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import Markdown from "@/components/Markdown";
import JsonLd from "@/components/JsonLd";
import Reveal from "@/components/motion/Reveal";
import { ArrowRight } from "@/components/icons";
import { getAllPosts, getPostBySlug } from "@/lib/posts";
import { articleSchema, breadcrumbSchema } from "@/lib/schema";
import { formatDate } from "@/lib/format";

// Statically generate one page per supplied Markdown file.
export function generateStaticParams() {
  return getAllPosts().map((post) => ({ slug: post.slug }));
}

// Per-post metadata built FROM the frontmatter (never recycled).
export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const post = getPostBySlug(slug);
  if (!post) return { title: "Post not found" };

  const canonical = `/blog/${post.slug}`;
  return {
    title: post.title,
    description: post.description,
    keywords: post.tags,
    alternates: { canonical },
    openGraph: {
      type: "article",
      title: post.title,
      description: post.description,
      url: canonical,
      publishedTime: post.date,
      tags: post.tags,
      // Dynamic per-post OG image is generated by ./opengraph-image.tsx and
      // injected automatically by Next; explicit type "article" set here.
    },
    twitter: {
      card: "summary_large_image",
      title: post.title,
      description: post.description,
    },
  };
}

export default async function BlogPostPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const post = getPostBySlug(slug);
  if (!post) notFound();

  return (
    <article className="py-16 sm:py-20">
      <div className="container-page">
        <JsonLd
          data={[
            articleSchema(post),
            breadcrumbSchema([
              { name: "Home", path: "/" },
              { name: "Writing", path: "/blog" },
              { name: post.title, path: `/blog/${post.slug}` },
            ]),
          ]}
        />

        {/* Breadcrumb (visible) */}
        <nav aria-label="Breadcrumb" className="text-sm text-muted">
          <ol className="flex flex-wrap items-center gap-2">
            <li>
              <Link href="/" className="hover:text-body">
                Home
              </Link>
            </li>
            <li aria-hidden>/</li>
            <li>
              <Link href="/blog" className="hover:text-body">
                Writing
              </Link>
            </li>
          </ol>
        </nav>

        <header className="mt-6 max-w-3xl">
          <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-muted">
            <time dateTime={post.date} className="tabular">
              {formatDate(post.date)}
            </time>
            <span aria-hidden>·</span>
            <span className="tabular">{post.readingTimeMin} min read</span>
          </div>
          <h1 className="mt-4 text-3xl font-semibold leading-tight tracking-tight sm:text-4xl lg:text-[2.75rem]">
            {post.title}
          </h1>
          <p className="mt-5 text-lg leading-relaxed text-muted">
            {post.description}
          </p>
          <div className="mt-5 flex flex-wrap gap-2">
            {post.tags.map((tag) => (
              <span
                key={tag}
                className="rounded-full border border-[var(--hairline)] px-2.5 py-0.5 text-xs text-muted"
              >
                {tag}
              </span>
            ))}
          </div>
        </header>

        <hr className="my-10 border-[var(--hairline)]" />

        <Reveal>
          {/* dropFirstH1: pages render their own <h1> above. */}
          <Markdown dropFirstH1>{post.content}</Markdown>
        </Reveal>

        {/* End-of-post CTA */}
        <div className="card mt-16 max-w-3xl p-7">
          <h2 className="text-xl font-semibold text-headline">
            Want this run against your real usage?
          </h2>
          <p className="mt-3 text-body/85">
            A $750 assessment turns your usage export into a line-by-line
            findings report - the same analysis above, with your dollar figures.
          </p>
          <div className="mt-6 flex flex-col gap-3 sm:flex-row">
            <Link href="/contact" className="btn-primary">
              Book an assessment
              <ArrowRight size={18} />
            </Link>
            <Link href="/blog" className="btn-ghost group">
              <ArrowRight
                size={16}
                className="rotate-180 transition-transform duration-300 group-hover:-translate-x-0.5"
              />
              All writing
            </Link>
          </div>
        </div>
      </div>
    </article>
  );
}
